language: ruby
rvm:
	- "1.8.7"
	- "1.9.3"
before_install: 
	- sudo apt-get update
	- sudo apt-get install -y xvfb chromium-browser iceweasel flashplugin-nonfree openjdk6 unzip
	- sudo wget http://chromedriver.googlecode.com/files/chromedriver_linux32_26.0.1383.0.zip 
	- sudo unzip chromedriver_linux32_26.0.1383.0.zip
	- sudo mv chromedriver /usr/local/bin/
script: "bundle exec rake"
