language: ruby
rvm:
  - "2.2.3"
  - "2.1.7"
  - "2.0.0"
  - "1.9"
before_install: 
  - sudo apt-get update
  - sudo apt-get install -y curl wget xvfb chromium-browser iceweasel flashplugin-installer openjdk-6-jdk unzip
  - sudo wget http://chromedriver.googlecode.com/files/chromedriver_linux32_26.0.1383.0.zip 
  - sudo unzip chromedriver_linux32_26.0.1383.0.zip
  - sudo mv chromedriver /usr/local/bin/
script: "bundle exec rake"
