sudo: required

language: ruby

services:
  - docker

before_install:
  - cat docker/Dockerfile | docker build -t kalw/wptrb -
  
script:
  - docker run --rm -ti --entrypoint "bash -c 'source /etc/profile.d/rvm.sh && bundle exec rake'" kalw/wptrb
