source 'https://rubygems.org'
gem 'watir-webdriver'
#gem 'watir-webdriver-performance'
gem 'headless'
gem 'selenium-webdriver', '=2.45.0'
#gem 'browsermob-proxy'
gem 'har'
gem 'logger'
gem 'sinatra', '=1.3.3'
gem 'sinatra-contrib'
gem 'sinatra-twitter-bootstrap'
#gem 'em-http-request'
#gem 'faye-websocket'
gem 'json'
gem 'trollop'
gem 'rake'
#gem 'rack-test'
#gem 'test-unit'
gem 'awesome_print'
gem 'haml'
#gem 'webkit_remote'
gem 'webrick'
gem 'arachni'
gem 'rest_client'
#gem 'fakeredis'
#gem 'resque'
gem 'zip'
gem 'rmagick', '2.13.2'
gem 'streamio-ffmpeg'
